version: "3"

services:
  temperature:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn temperature_service:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  collector:
    build:
      context: .
    command: uvicorn collector_service:app --host 0.0.0.0 --port 8001
    volumes:
      - ./data:/app/data
    ports:
      - "8001:8001"
    depends_on:
      - temperature

  viewer:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn viewer_service:app --host 0.0.0.0 --port 8002
    volumes:
      - ./data:/app/data

    ports:
      - "8002:8002"
