version: "3"

services:
  temperature:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn temperature_service:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  collector:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn collector_service:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    depends_on:
      - temperature
